- name: Downloading Erlang
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: Downloading RabbitMQ
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Installation of Erlang
  ansible.builtin.yum:
    name: erlang
    state: installed

- name: Installation of Erlang
  ansible.builtin.yum:
    name: rabbitmq-server
    state: installed

- name: Start the service
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: rabbitmq-server

- name: Adding rabbitMQ user
  community.rabbitmq.rabbitmq_user:
    user: "{{ lookup('amazon.aws.aws_ssm', 'env.{{component}}.amqp_user', region='us-east-1' ) }}"
    password: "{{ lookup('amazon.aws.aws_ssm', 'env.{{component}}.amqp_pass', region='us-east-1' ) }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

