- name: Downloading Erlang
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: Downloading RabbitMQ
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Installation of Erlang
  ansible.builtin.yum:
    state: installed
    name: 
      - erlang
      - rabbitmq-server

- name: Start the service
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: rabbitmq-server

- name: Adding rabbitMQ user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

