alert_files:
 - service_down_alerts.yml
 - cpu_data.yml

node_exporter_url: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
node_exporter_dir: "{{ node_exporter_url | split('/') | last | regex_replace('.tar.gz','')}}"

components:
  - { name: '{{env}}-cart-asg', service_name: cart }
  - { name: '{{env}}-catalogue-asg', service_name: catalogue }
  - { name: '{{env}}-frontend-asg', service_name: nginx }
  - { name: '{{env}}-user-asg', service_name: user }
  - { name: '{{env}}-shipping-asg', service_name: shipping }
  - { name: '{{env}}-payment-asg', service_name: payment }


