alert_files:
 - service_down_alerts.yml
 - cpu_data.yml

node_exporter_url: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
node_exporter_dir: "{{ node_exporter_url | split('/') | last | regex_replace('.tar.gz','')}}"

components:
  - { name: dev-cart-asg, service_name: cart }
  - { name: dev-catalogue-asg, service_name: catalogue }
  - { name: dev-frontend-asg, service_name: nginx }
  - { name: dev-user-asg, service_name: user }
  - { name: dev-shipping-asg, service_name: shipping }
  - { name: dev-payment-asg, service_name: payment }


