- name: Copying prometheus.yml file to a directory
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Alert rules
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /opt/prometheus/{{ item }}
  loop: "{{ alert_files }}"

- name: Restart the service
  ansible.builtin.systemd:
    state: restarted
    name: prometheus

- name: Update AlertManager Configuration
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml

- name: Restart alertmanager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted