- name: Add the user 'roboshop'
  ansible.builtin.user:
    name: roboshop
  

- name: Remove /app
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create a directory /app
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download zip files
  ansible.builtin.unarchive:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: /app
    remote_src: no


