- name: Setting the hostname
  ansible.builtin.shell: set-hostname {{ component }}




- name: Importing prometheus role, node exporter tasks
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter

- name: Importing elk role, filebeat tasks
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat
  when: filebeat
