- name: Nodejs repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: NodeJS setup
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Import the basic_setup task
  ansible.builtin.import_tasks:
    file: basic_setup.yml


- name: Install NodeJS Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Import the schema_setup task
  ansible.builtin.import_tasks:
    file: schema_setup.yml
  when: db_type is defined

- name: Import the systemd task
  ansible.builtin.import_tasks:
    file: systemd_setup.yml