- name: MongoDB configuration
  when: db_type=="mongo"
  block:
    - name: Mongo setup
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install the latest version of mongo client
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed
    - name: Downloading PEM file
      ansible.builtin.get_url:
        url: https://truststore.pki.rds.amazonaws.com/us-east-1/us-east-1-bundle.pem
        dest: /app/docdb.pem

    - name: Load the schema
      ansible.builtin.shell: mongo --ssl --host {{ lookup('amazon.aws.aws_ssm', '{{env}}.docdb.endpoint', region='us-east-1' ) }}:27017 --sslCAFile /app/docdb.pem --username {{ lookup('amazon.aws.aws_ssm', '{{env}}.docdb.user', region='us-east-1' ) }} --password {{ lookup('amazon.aws.aws_ssm', '{{env}}.docdb.pass', region='us-east-1' ) }} </app/schema/{{ component }}.js


- name: MySQL DB configuration
  when: db_type=="mysql"
  block:
    - name: MySQL setup
      ansible.builtin.yum:
        name: mysql
        state: installed

    - name: Load the schema
      ansible.builtin.shell: mysql -h {{ lookup('amazon.aws.aws_ssm', '{{env}}.rds.endpoint', region='us-east-1' ) }} -u{{ lookup('amazon.aws.aws_ssm', '{{env}}.rds.user', region='us-east-1' ) }} -p{{ lookup('amazon.aws.aws_ssm', '{{env}}.rds.password', region='us-east-1' ) }} < /app/schema/{{ component }}.sql

        


